In [79]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
import seaborn as sns # Seaborn is a useful library for Data Visualisation
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler, LabelBinarizer
from sklearn.metrics import classification_report, accuracy_score
from sklearn.tree import plot_tree
from sklearn.tree import export_graphviz 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [80]:
from sklearn.preprocessing import RobustScaler

df = pd.read_csv('F:/uit/AI/Finallllll/onlinefraud.csv')

In [81]:
df.head(10)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0

In [82]:
df.type.value_counts()

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [83]:
d = {'CASH_OUT': 0, 'PAYMENT': 1, 'CASH_IN': 2, 'TRANSFER': 3, 'DEBIT': 4}
df['type'] = df['type'].map(d)
# df["isFraud"] = df["isFraud"].map({0: "No Fraud", 1: "Fraud"})
df.head(10)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,1,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0
1,1,1,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0
2,1,3,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0
3,1,0,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0
4,1,1,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0
5,1,1,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0
6,1,1,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0
7,1,1,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0
8,1,1,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,0
9,1,4,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0

In [85]:
df.dtypes

step                int64
type                int64
amount            float64
nameOrig           object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest           object
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object

In [86]:
df.describe(include='all')

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6362620,6.362620e+06,6.362620e+06,6362620,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
unique,NaN,NaN,NaN,6353307,NaN,NaN,2722362,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,C1677795071,NaN,NaN,C1286084959,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,3,NaN,NaN,113,NaN,NaN,NaN,NaN
mean,2.433972e+02,1.055307e+00,1.798619e+05,NaN,8.338831e+05,8.551137e+05,NaN,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,9.808966e-01,6.038582e+05,NaN,2.888243e+06,2.924049e+06,NaN,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,0.000000e+00,1.338957e+04,NaN,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,1.000000e+00,7.487194e+04,NaN,1.420800e+04,0.000000e+00,NaN,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.000000e+00,2.087215e+05,NaN,1.073152e+05,1.442584e+05,NaN,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,4.000000e+00,9.244552e+07,NaN,5.958504e+07,4.958504e+07,NaN,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

Robust Scaler

In [87]:
new_df = df.copy()
new_df['amount'] = RobustScaler().fit_transform(new_df['amount'].to_numpy().reshape(-1, 1))
new_df['oldbalanceOrg'] = RobustScaler().fit_transform(new_df['oldbalanceOrg'].to_numpy().reshape(-1, 1))
new_df['oldbalanceDest'] = RobustScaler().fit_transform(new_df['oldbalanceDest'].to_numpy().reshape(-1, 1))
new_df.describe(include='all')

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6362620,6.362620e+06,6.362620e+06,6362620,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
unique,NaN,NaN,NaN,6353307,NaN,NaN,2722362,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,C1677795071,NaN,NaN,C1286084959,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,3,NaN,NaN,113,NaN,NaN,NaN,NaN
mean,2.433972e+02,1.055307e+00,5.374952e-01,NaN,7.638017e+00,8.551137e+05,NaN,1.026467e+00,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,9.808966e-01,3.091447e+00,NaN,2.691365e+01,2.924049e+06,NaN,3.604505e+00,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,-3.833062e-01,NaN,-1.323951e-01,0.000000e+00,NaN,-1.407216e-01,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,0.000000e+00,-3.147585e-01,NaN,-1.323951e-01,0.000000e+00,NaN,-1.407216e-01,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,1.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,1.543090e-17,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.000000e+00,6.852415e-01,NaN,8.676049e-01,1.442584e+05,NaN,8.592784e-01,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,4.000000e+00,4.728907e+02,NaN,5.551017e+02,4.958504e+07,NaN,3.773800e+02,3.561793e+08,1.000000e+00,1.000000e+00

In [88]:
missing_data = new_df.isnull().sum()
print(missing_data)

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

Train Test Split

In [89]:
from sklearn.model_selection import train_test_split

X = new_df[["type","amount","oldbalanceOrg","oldbalanceDest"]]

y = new_df['isFraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

Decision Tree Classifier

In [90]:
clf = DecisionTreeClassifier()


clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(classification_report(y_test, y_pred))
#precision: biết True bắt True
#recall: biết False bắt False

Accuracy: 0.9994077911300691
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1588610
           1       0.76      0.79      0.77      2045

    accuracy                           1.00   1590655
   macro avg       0.88      0.90      0.89   1590655
weighted avg       1.00      1.00      1.00   1590655

Random Forest Classifier

In [92]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf_model = rf.fit(X_train, y_train)
print(classification_report(y_test, rf_model.predict(X_test), target_names=['Not Fraud', 'Fraud']))

              precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00   1588610
       Fraud       0.92      0.74      0.82      2045

    accuracy                           1.00   1590655
   macro avg       0.96      0.87      0.91   1590655
weighted avg       1.00      1.00      1.00   1590655

Logistic Regression

In [93]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr_model = lr.fit(X_train, y_train)
print(classification_report(y_test, lr_model.predict(X_test), target_names=['Not Fraud', 'Fraud']))

              precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00   1588610
       Fraud       0.92      0.02      0.03      2045

    accuracy                           1.00   1590655
   macro avg       0.96      0.51      0.52   1590655
weighted avg       1.00      1.00      1.00   1590655

In [94]:
import xgboost as xgb
exb = xgb.XGBClassifier()
exb.fit(X_train, y_train)
print(classification_report(y_test, exb.predict(X_test), target_names=['Not Fraud', 'Fraud']))

              precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00   1588610
       Fraud       0.90      0.74      0.81      2045

    accuracy                           1.00   1590655
   macro avg       0.95      0.87      0.90   1590655
weighted avg       1.00      1.00      1.00   1590655

SMOTE

In [95]:
from collections import Counter
print('Original dataset shape %s' %Counter(y_train))

Original dataset shape Counter({0: 4765797, 1: 6168})

In [96]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
print('Resample dataset shape %s' %Counter(y_resampled))

Resample dataset shape Counter({0: 4765797, 1: 4765797})

In [97]:
clf = DecisionTreeClassifier()


clf.fit(X_resampled, y_resampled)
y_pred = clf.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(classification_report(y_test, y_pred))
#precision: biết True bắt True
#recall: biết False bắt False

Accuracy: 0.9985980618047282
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1588610
           1       0.48      0.92      0.63      2045

    accuracy                           1.00   1590655
   macro avg       0.74      0.96      0.81   1590655
weighted avg       1.00      1.00      1.00   1590655

In [98]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf_model = rf.fit(X_resampled, y_resampled)
print(classification_report(y_test, rf_model.predict(X_test), target_names=['Not Fraud', 'Fraud']))

              precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00   1588610
       Fraud       0.52      0.94      0.67      2045

    accuracy                           1.00   1590655
   macro avg       0.76      0.97      0.83   1590655
weighted avg       1.00      1.00      1.00   1590655

In [99]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr_model = lr.fit(X_resampled, y_resampled)
print(classification_report(y_test, lr_model.predict(X_test), target_names=['Not Fraud', 'Fraud']))

              precision    recall  f1-score   support

   Not Fraud       1.00      0.90      0.95   1588610
       Fraud       0.01      0.63      0.02      2045

    accuracy                           0.90   1590655
   macro avg       0.50      0.76      0.48   1590655
weighted avg       1.00      0.90      0.94   1590655

In [100]:
import xgboost as xgb
exb = xgb.XGBClassifier()
exb.fit(X_resampled, y_resampled)
print(classification_report(y_test, exb.predict(X_test), target_names=['Not Fraud', 'Fraud']))

              precision    recall  f1-score   support

   Not Fraud       1.00      1.00      1.00   1588610
       Fraud       0.24      0.99      0.38      2045

    accuracy                           1.00   1590655
   macro avg       0.62      0.99      0.69   1590655
weighted avg       1.00      1.00      1.00   1590655

In [101]:
from sklearn.ensemble import BaggingClassifier

clf = BaggingClassifier()
clf.fit(X_resampled, y_resampled)
print(classification_report(y_test, clf.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1588610
           1       0.52      0.93      0.67      2045

    accuracy                           1.00   1590655
   macro avg       0.76      0.97      0.83   1590655
weighted avg       1.00      1.00      1.00   1590655